['*.{ts,tsx,js}', '!commitlint.config.cjs']:
  - 'eslint --cache --cache-location ./node_modules/.cache/.eslintcache --ext .ts,.tsx . --fix --max-warnings=0'
  - 'prettier --loglevel warn --cache --write'
'*.{json,yml,scss}': 'prettier --loglevel warn --cache --write'
